### ISSUE TITLE
Add file module

### ISSUE THREAD

**Issue by J3RN** [gleam-lang/erlang#15]
I'm actively working on this, but am opening this issue to
1. allow the community to provide input on what they'd like to see while I work on it
2. provide documentation for the next fellow should I be hit by a bus

After reading through Erlang's `file` module and Node.js' `fs`, what follows is my plan. The format is
```
Erlang file function (Node.js fs function)
```

### Must-Haves

- [x] `read_file` (`readFileSync`)
- [x] `write_file` (`writeFileSync`)
- [x] `delete` (`rmSync`)

### Maybe
_Things that are not *mandatory*, but might be nice to have._

- [ ] Various `IODevice`
  - [ ] `open` (`openSync`)
  - [ ] `close` (`closeSync`)
  - [ ] `read` (`readSync`)
  - [ ] `write` (`writeSync`)
  - [ ] `read_line` (???)
  - [ ] `position`, `pread`, `pwrite` (???)
  - Double Maybe: `sync`, `truncate` (`fsyncSync` and `ftruncateSync`)?
- [ ] `copy`, `rename` (`copyFileSync`, `renameFileSync`)
- [ ] `del_dir{,_r}`, `list_dir{,_all}`, `make_dir` (`rmdirSync`, `readdirSync`, `mkdirSync`)
  - Erlang has no `copy_dir`, whereas Node.js has `cpSync`
- [ ] `allocate` (???—Perhaps could just do a `writeFileSync` with null bytes)
- [ ] `read_file_info`, `read_link_info`, `write_file_info` (`fstatSync`, `linkSync`)
- [ ] `change_mode`, `change_owner`, `change_group` (`chmodSync`, `lchmodSync`, `chownSync`, `lchownSync`)
- [ ] `make_{,sym}link`, `read_link` (`{,sym}linkSync`, `readlinkSync`)

### What?
_I don't understand these functions, or how they are different from other functions._
- [ ] `native_name_encoding`
- [ ] `read_link_all`

### Not for now
_I don't think these functions would be good to add at this time_
- [ ] `sendfile`; Does Gleam have a notion of "Socket"? (???—No clue how to support this for Node.js)
- [ ] `datasync` (`fdatasyncSync` or `fsyncSync`, maybe, as the docs imply this is actually different.)
- [ ] `set_cwd`, `get_cwd`
- [ ] `eval`, `script`
- [ ] `path_consult`; I like this function, but assume it sees rather limited real-world use.
- [ ] `path_eval`, `path_open`, `path_script`
- [ ] `pid2name`

**Comment by lpil** [comment]
Closing this as we have the wonderful https://hexdocs.pm/simplifile/
