### ISSUE TITLE
charlist to string and UTF8

### ISSUE THREAD

**Issue by jeromede** [gleam-lang/erlang#25]
I think <https://github.com/gleam-lang/erlang/blob/main/src/gleam/erlang/charlist.gleam> should use

```
unicode:characters_to_binary(CharList, utf8, utf8)
```

instead of

```
erlang:list_to_binary(CharList)
```

etc.

For example:

```
Eshell V13.1.2  (abort with ^G)
1> erlang:list_to_binary("Jérôme").
<<"Jérôme">>
2> unicode:characters_to_binary("Jérôme", utf8, utf8).
<<"Jérôme"/utf8>>
```

Got caught with my first try with Gleam when I wanted to:

```
gleam run Jérôme
```

with

```
import gleam/io
import gleam/string
import gleam/erlang

pub fn main() {
  let args = erlang.start_arguments()
  let name = string.join(args, " ")
  io.println("Hello " <> name <> "!")
}
```

`string.join` fails.

**Comment by lpil** [comment]
Good find! Would you like to make a pull request? 🙏

**Comment by jeromede** [comment]
Yes, I was thinking about that, that would be the most helpful I guess. I just need to make a bit sense of it all, I just started exploring Gleam yesterday night :-) But I will, just not today.

**Comment by lpil** [comment]
Coolio, feel free to at any time if no one else picks up this issue :)

**Comment by jeromede** [comment]
OK, I found time today :-)
