### ISSUE TITLE
proposal: support ETS (Erlang Term Storage) module 

### ISSUE THREAD

**Issue by septemhill** [gleam-lang/erlang#39]
Since we have `otp` and `erlang` packages now, I think we should support `ets` feature. 
But the thing I'm not sure is that, should it be part of this package, or we should create one more repository for `ets` ?

**Comment by lpil** [comment]
I did a search for "ETS" and found this package, does it meet your needs? https://packages.gleam.run/?search=ETS

**Comment by septemhill** [comment]
Ah, yes, thanks

Out of curious, ETS is part of Erlang, should we make it be part of Gleam officially ? 
What I mean is, usually people would use built-in / stdlib / maintained by official team members packages,
if they don't provide (or those packages aren't convenient) then people would search 3rd-party libs for alternative, 

So what I'm thinking is, ETS is a basically feature in the Erlang, should this package wrap all of Erlang features 
and provide basic implementation for Gleam users ? 

Like #15, we have a plan to add file module into this package, but before we finished that, maybe we can find some packages for alternative, then should we just let #15 go ?

**Comment by lpil** [comment]
#15 has been completed, see this excellent library https://github.com/bcpeinhardt/simplifile

There's no advantage to having something be maintained by core. We already have many large projects to maintain, so anything else that gets maintained by us will likely have much less time spent on it than if it is done by community members that don't have as high a workload.

There's also no particular goal to wrap all Erlang APIs. There's a great quantity of them, many are not useful, and some are not typable. Instead this package aims to provide some of the most widely used parts, to avoid many packages having to reimplement them.

**Comment by septemhill** [comment]
@lpil Thanks for your reply, I understood. I'll close this issue

**Comment by lpil** [comment]
Thank you 💜
