### ISSUE TITLE
Graceful shutdown of an application

### ISSUE THREAD

**Issue by yerTools** [gleam-lang/erlang#43]
Hi,

I'm quite new to Gleam, so maybe this is not an issue, but I would like to shut down my application gracefully. I'm building a Full-Stack application with Wisp as my server.

I use `process.sleep_forever()` at the end of my main function to keep the main thread running. I also use SQLite as my database and would love to create a shutdown log and close the connection before exiting. I wrote this application in Go before, and there I can easily listen for `Interrupt`, `SIGTERM`, or `SIGINT`.

My idea for this library is to add something like `process.wait_for_shutdown()`, which is a function that sleeps until it catches exactly one interrupt and then returns. This way, you could invoke a shutdown routine but still kill the application with a second interrupt.

Maybe also provide an argument (or have a second function) which can be used for a timeout. For example: `process.wait_for_shutdown_with_timeout(5 seconds or whatever)`. This call would also wait until an interrupt, then start a timer with the provided delay and then return. If the timer has expired before the application closed itself, it will be killed. This way, you can be sure that your application will terminate after a single interrupt was sent to the process.

---

I don't have any experience with Erlang or BEAM, so I don't know how much work this would be.
I also don't know if there is any way to achieve something like this behavior only with Gleam code. After a few searches, I did chat with ChatGPT, and it suggested the following:

```gleam
fn handle_exit_signal(signal: process.ExitMessage) -> Nil {
  // Close the database connection here
  io.println("Received exit signal:")
  io.debug(signal)
  io.println("Closing database connection...")
  // Your code to close the database connection
  Nil
}

pub fn main(){
  process.trap_exits(True)

  // Create a selector to handle exit signals
  let selector =
    process.new_selector()
    |> process.selecting_trapped_exits(handle_exit_signal)

  // Run your main application logic here
  io.println("Application is running...")

  // Wait for an exit signal
  let _ = process.select_forever(selector)

  io.println("Application is shutting down.")
}
```

But this didn't work, and if I press <kbd>Ctrl</kbd> + <kbd>C</kbd> after running `gleam run`, it just shows the:

>    BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo  
>    (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution

dialog. The same thing happens after using `gleam export erlang-shipment` and starting it with `./entrypoint.sh run`, even if I use the `kill -2 <process id>` command to send a `SIGINT` to the process.

---

Thank you very much! :smile:
\- Felix

**Comment by lpil** [comment]
Hello! You are trapping Erlang process exits rather than operating system signals there. You may be able to use [this](https://www.erlang.org/doc/man/kernel_app.html#erl_signal_server) to respond to OS signals, but I have not tried this myself. There may be other approaches too.

I'd advise to not use ChatGPT etc for Gleam. It doesn't know anything about Gleam and so will just make up lies and waste your time.

**Comment by lpil** [comment]
Nice! It would be out of scope for this library as it's not related to using Erlang.
