### ISSUE TITLE
gleam/erlang/file not working

### ISSUE THREAD

**Issue by chuckberrypi** [gleam-lang/erlang#50]
I'm having an issue using the `file` module. Here's the code I'm trying to run, in its entirety: 

```
import gleam/erlang/charlist
import gleam/erlang/atom
import gleam/erlang/os
import gleam/erlang/process
// import gleam/erlang/file
import gleam/io

pub fn main() {
  io.println("Hello from road_to_gm!")
}
```

It complies, but then fails if I uncomment the `import gleam/erlang/file` line. Any advice?

**Comment by shakna-israel** [comment]
Hey @chuckberrypi , did you work out what you did here? I'm hitting something similar:

> error: Unknown module
>  ┌─ /home/jmilne/webthing/src/webthing.gleam:3:1
>  │
>3 │ import gleam/erlang/file
>  │ ^^^^^^^^^^^^^^^^^^^^^^^^

> No module has been found with the name `gleam/erlang/file`.

**Comment by lpil** [comment]
That module does not exist. It did once, but hasn't since long before Gleam was released.

**Comment by shakna-israel** [comment]
🤦 My bad.

[0.14](https://hexdocs.pm/gleam_erlang/0.14.0/gleam/erlang/file.html)'s file docs still show up when just looking for "gleam file open" on a search engine.

**Comment by lpil** [comment]
Ah, Google causing us problems again. I will try and get them to deindex that page soon.
