### ISSUE TITLE
Erlang os.cmd function to run shell commands in Gleam code

### ISSUE THREAD

**Issue by Askath** [gleam-lang/erlang#51]
Hello, 
I would love to implement the os.cmd/1 and os.cmd/2 from the erlang os module. 
I tend to write more and more small tools that could use this without having to constantly reimplement it with 

`@external(erlang, "os", "cmd")
fn execute(cmd: charlist.Charlist) -> String
`
[Erlang Doc for cmd/1 and cmd/2](https://www.erlang.org/doc/apps/kernel/os.html#cmd/2)

I would like to try my hands on an implementation if thats okay :)

**Comment by lpil** [comment]
Hello! There's some packages for this today. The package site is useful at these times: https://packages.gleam.run/?search=shell
