### ISSUE TITLE
[feat] Add some kind of `process.call_forever` function.

### ISSUE THREAD

**Issue by BlockListed** [gleam-lang/erlang#60]
An equivalent of erlang's `gen_server.call(ServerRef, Request, infinity)` (a gen_server call with an infinite timeout) would be very useful.
The current `actor.call` does not have this feature, since it only takes finite timeouts.

**Comment by BlockListed** [comment]
I'm calling an actor and don't want a timeout.
Specifically I'm writing a CLI for my application, which runs over TCP and the TCP part is wrapped in an actor.
My `get_line` calls to the actor needn't have a timeout, since it's waiting for user input.

**Comment by lpil** [comment]
Makes sense! Thank you
