### ISSUE TITLE
Add a way to drop a `Subject` from a `Selector`.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/erlang#61]
In a long-running process you might find it useful to create many short-lived `Subject`s to hand to other processes. If you're doing this you're likely going to be calling `merge_selector` with a process's _existing_ selector quite a lot so you can continue receiving messages from anything else you had previously set up.

This introduces a memory leak because even if you know the thing consuming your `Subject` has died or no longer needs to send your process messages, there's no way to drop the selector for _just this subject_: you are effectively growing a dict forever! 

---

I'd propose a `deselecting` function as a dual to `selecting` that takes a `Selector` and a `Subject` and removes any associated handler from the map.

**Comment by lpil** [comment]
Definitely.
