### ISSUE TITLE
Fix `demonitor_process` return type

### ISSUE THREAD

**Issue by chouzar** [gleam-lang/erlang#69]
The `process.demonitor_process` function [has the signature](https://hexdocs.pm/gleam_erlang/gleam/erlang/process.html#demonitor_process): 

```gleam
pub fn demonitor_process(monitor monitor: ProcessMonitor) -> Nil
```

Trying this code: 

```gleam
let Nil = process.demonitor_process(monitor)
```

I always get a `{badmatch, true}`. [Erlang's demonitor function](https://www.erlang.org/doc/apps/erts/erlang.html#demonitor/1) seems to always return `true` even if already demonitored.

**Comment by lpil** [comment]
Oh no! Thank you
